### PR TITLE
Function Lab1 - Uploaded

### PR DESCRIPTION
**Pull request by HessaAlmasaad**
Function Lab1 - Uploaded 
Hessa Almasaad

### CODE REVIEW

**Comment by wijdan-alharbi** [comment]
Well done. however, please make sure to include function documentation then print it.

**Comment by HessaAlmasaad** [comment]
Sure, I did it now it is updated

**Comment by wijdan-alharbi** [comment]
Thank you for fast response .

**Comment by HessaAlmasaad** [comment]
Your Welcome miss Wijdan

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request closed without merging**
